# Swift Package Index build configuration.
# https://swiftpackageindex.com/swiftpackageindex/spimanifest/documentation/spimanifest/commonusecases
version: 1
builder:
  configs:
    - documentation_targets: [Markdown]
